//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashManager.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashManager.Logic.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home
        ///.Furniture
        ///.Cleaning
        ///.Others
        ///Others
        ///Food
        ///.Fastfood
        ///.Restaurant
        ///.Shop
        ///.Tea
        ///.Others
        ///Gifts
        ///.Family
        ///.Friends
        ///.Others
        ///Fun
        ///.Games
        ///.Cinema
        ///.Books
        ///Car
        ///.Parking
        ///.Credit
        ///.Servis
        ///.Parts
        ///.Fuel
        ///Holiday
        ///.Food
        ///.Others
        ///Health
        ///.Drugs
        ///.Others
        ///Animals
        ///.Food
        ///.Toys
        ///.Vet
        ///.Drugs
        ///.Others.
        /// </summary>
        internal static string DefaultCategories {
            get {
                return ResourceManager.GetString("DefaultCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex 1.
        /// </summary>
        internal static string DefaultExternalStock {
            get {
                return ResourceManager.GetString("DefaultExternalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account 1.
        /// </summary>
        internal static string DefaultUserBankAccount {
            get {
                return ResourceManager.GetString("DefaultUserBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string DefaultWallet {
            get {
                return ResourceManager.GetString("DefaultWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        internal static string Gifts {
            get {
                return ResourceManager.GetString("Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer in.
        /// </summary>
        internal static string TransferIn {
            get {
                return ResourceManager.GetString("TransferIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer out.
        /// </summary>
        internal static string TransferOut {
            get {
                return ResourceManager.GetString("TransferOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
