//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashManager.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add correction transaction.
        /// </summary>
        public static string AddCorrectionTransaction {
            get {
                return ResourceManager.GetString("AddCorrectionTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will add additional transaction to leave history untouched.
        ///Case: &quot;The history (and balance) is ok, but that transaction has wrong value, anyway there as another transaction, which I can&apos;t remember and that transaction made history as it is now..
        /// </summary>
        public static string AddCorrectionTransactionTooltip {
            get {
                return ResourceManager.GetString("AddCorrectionTransactionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom balance.
        /// </summary>
        public static string AddCustomBalance {
            get {
                return ResourceManager.GetString("AddCustomBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add position.
        /// </summary>
        public static string AddPosition {
            get {
                return ResourceManager.GetString("AddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rule.
        /// </summary>
        public static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add stock.
        /// </summary>
        public static string AddStock {
            get {
                return ResourceManager.GetString("AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add transaction.
        /// </summary>
        public static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add type.
        /// </summary>
        public static string AddTransactionType {
            get {
                return ResourceManager.GetString("AddTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced payment mode.
        /// </summary>
        public static string AdvancePaymentMode {
            get {
                return ResourceManager.GetString("AdvancePaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net/tax/gross instead simple value.
        /// </summary>
        public static string AdvancePaymentModeTooltip {
            get {
                return ResourceManager.GetString("AdvancePaymentModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analitics.
        /// </summary>
        public static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any of words.
        /// </summary>
        public static string AnyOfWords {
            get {
                return ResourceManager.GetString("AnyOfWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append mode.
        /// </summary>
        public static string AppendMode {
            get {
                return ResourceManager.GetString("AppendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application sounds.
        /// </summary>
        public static string ApplicationSounds {
            get {
                return ResourceManager.GetString("ApplicationSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for category delete.
        /// </summary>
        public static string AskForCategoryDelete {
            get {
                return ResourceManager.GetString("AskForCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for category move.
        /// </summary>
        public static string AskForCategoryMove {
            get {
                return ResourceManager.GetString("AskForCategoryMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for mass replace perform.
        /// </summary>
        public static string AskForMassReplacePerform {
            get {
                return ResourceManager.GetString("AskForMassReplacePerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for position delete.
        /// </summary>
        public static string AskForPositionDelete {
            get {
                return ResourceManager.GetString("AskForPositionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for transaction delete.
        /// </summary>
        public static string AskForTransactionDelete {
            get {
                return ResourceManager.GetString("AskForTransactionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup database on app close.
        /// </summary>
        public static string BackupDbOnClose {
            get {
                return ResourceManager.GetString("BackupDbOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup database on app start.
        /// </summary>
        public static string BackupDbOnStart {
            get {
                return ResourceManager.GetString("BackupDbOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance update mode.
        /// </summary>
        public static string BalanceUpdateMode {
            get {
                return ResourceManager.GetString("BalanceUpdateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill preview.
        /// </summary>
        public static string BillPreview {
            get {
                return ResourceManager.GetString("BillPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book date.
        /// </summary>
        public static string BookDate {
            get {
                return ResourceManager.GetString("BookDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories plot.
        /// </summary>
        public static string CategoriesPlot {
            get {
                return ResourceManager.GetString("CategoriesPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Category Manager.
        /// </summary>
        public static string CategoryManagerHeader {
            get {
                return ResourceManager.GetString("CategoryManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #,##0.
        /// </summary>
        public static string CountFormat {
            get {
                return ResourceManager.GetString("CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Balance Manager.
        /// </summary>
        public static string CustomBalanceManager {
            get {
                return ResourceManager.GetString("CustomBalanceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom balances.
        /// </summary>
        public static string CustomBalances {
            get {
                return ResourceManager.GetString("CustomBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DefaultCategoryName {
            get {
                return ResourceManager.GetString("DefaultCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default external stock.
        /// </summary>
        public static string DefaultExternalStock {
            get {
                return ResourceManager.GetString("DefaultExternalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default income type.
        /// </summary>
        public static string DefaultIncomeType {
            get {
                return ResourceManager.GetString("DefaultIncomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default outcome type.
        /// </summary>
        public static string DefaultOutcomeType {
            get {
                return ResourceManager.GetString("DefaultOutcomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop bills here.
        /// </summary>
        public static string DropBillsHere {
            get {
                return ResourceManager.GetString("DropBillsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit date.
        /// </summary>
        public static string EditDate {
            get {
                return ResourceManager.GetString("EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all.
        /// </summary>
        public static string EnableAll {
            get {
                return ResourceManager.GetString("EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex stock.
        /// </summary>
        public static string ExStock {
            get {
                return ResourceManager.GetString("ExStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External stock.
        /// </summary>
        public static string ExternalStock {
            get {
                return ResourceManager.GetString("ExternalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of month.
        /// </summary>
        public static string FirstDayOfTheMonth {
            get {
                return ResourceManager.GetString("FirstDayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First month.
        /// </summary>
        public static string FirstMonth {
            get {
                return ResourceManager.GetString("FirstMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default categories.
        /// </summary>
        public static string GenerateDefaultCategories {
            get {
                return ResourceManager.GetString("GenerateDefaultCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default stocks.
        /// </summary>
        public static string GenerateDefaultStocks {
            get {
                return ResourceManager.GetString("GenerateDefaultStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default tags.
        /// </summary>
        public static string GenerateDefaultTags {
            get {
                return ResourceManager.GetString("GenerateDefaultTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default types.
        /// </summary>
        public static string GenerateDefaultTypes {
            get {
                return ResourceManager.GetString("GenerateDefaultTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate missing stocks.
        /// </summary>
        public static string GenerateMissingStocks {
            get {
                return ResourceManager.GetString("GenerateMissingStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate sample transactions.
        /// </summary>
        public static string GenerateSampleTransactions {
            get {
                return ResourceManager.GetString("GenerateSampleTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        public static string Gross {
            get {
                return ResourceManager.GetString("Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Home.
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string ImportHeader {
            get {
                return ResourceManager.GetString("ImportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        public static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse - display not matching.
        /// </summary>
        public static string InverseMatching {
            get {
                return ResourceManager.GetString("InverseMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string IsTransfer {
            get {
                return ResourceManager.GetString("IsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day of month.
        /// </summary>
        public static string LastDayOfTheMonth {
            get {
                return ResourceManager.GetString("LastDayOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last edit.
        /// </summary>
        public static string LastEdit {
            get {
                return ResourceManager.GetString("LastEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last edit date.
        /// </summary>
        public static string LastEditDate {
            get {
                return ResourceManager.GetString("LastEditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load content as tree.
        /// </summary>
        public static string LoadContentAsTree {
            get {
                return ResourceManager.GetString("LoadContentAsTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock tax.
        /// </summary>
        public static string LockTax {
            get {
                return ResourceManager.GetString("LockTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manage.
        /// </summary>
        public static string ManageHeader {
            get {
                return ResourceManager.GetString("ManageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual stock update.
        /// </summary>
        public static string ManualStockUpdate {
            get {
                return ResourceManager.GetString("ManualStockUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass replace.
        /// </summary>
        public static string MassReplace {
            get {
                return ResourceManager.GetString("MassReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass replacer.
        /// </summary>
        public static string MassReplacer {
            get {
                return ResourceManager.GetString("MassReplacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match all elements.
        /// </summary>
        public static string MatchAllElements {
            get {
                return ResourceManager.GetString("MatchAllElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        public static string NetValue {
            get {
                return ResourceManager.GetString("NetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New position.
        /// </summary>
        public static string NewPosition {
            get {
                return ResourceManager.GetString("NewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next day.
        /// </summary>
        public static string NextDay {
            get {
                return ResourceManager.GetString("NextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        public static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next year.
        /// </summary>
        public static string NextYear {
            get {
                return ResourceManager.GetString("NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No balance change.
        /// </summary>
        public static string NoBalanceChange {
            get {
                return ResourceManager.GetString("NoBalanceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock balance value will stay the same.
        ///Case: &quot;I just made a mistake, but stock balance is still ok&quot;..
        /// </summary>
        public static string NoBalanceChangeTooltip {
            get {
                return ResourceManager.GetString("NoBalanceChangeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse.
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser.
        /// </summary>
        public static string Parser {
            get {
                return ResourceManager.GetString("Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform.
        /// </summary>
        public static string Perform {
            get {
                return ResourceManager.GetString("Perform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform replaces.
        /// </summary>
        public static string PerformReplaces {
            get {
                return ResourceManager.GetString("PerformReplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart application to use newer version.
        /// </summary>
        public static string PleaseRestartApplicationToUseNewerVersion {
            get {
                return ResourceManager.GetString("PleaseRestartApplicationToUseNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions search.
        /// </summary>
        public static string PositionSearch {
            get {
                return ResourceManager.GetString("PositionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position title.
        /// </summary>
        public static string PositionTitle {
            get {
                return ResourceManager.GetString("PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous day.
        /// </summary>
        public static string PreviousDay {
            get {
                return ResourceManager.GetString("PreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        public static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year.
        /// </summary>
        public static string PreviousYear {
            get {
                return ResourceManager.GetString("PreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you want to remove {0} category?.
        /// </summary>
        public static string QuestionDoYouWantToDeleteCategoryFormat {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToDeleteCategoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you want to move category {0} under category {1}?.
        /// </summary>
        public static string QuestionDoYouWantToMoveCategoryFormat {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToMoveCategoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to perform mass replace for all positions?.
        /// </summary>
        public static string QuestionDoYouWantToPerformMassReplaceOnAllPositions {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToPerformMassReplaceOnAllPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to perform mass replace for all transactions?.
        /// </summary>
        public static string QuestionDoYouWantToPerformMassReplaceOnAllTransactions {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToPerformMassReplaceOnAllTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to perform mass replace for: {0} positions?.
        /// </summary>
        public static string QuestionDoYouWantToPerformMassReplaceOnPositionsFormat {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToPerformMassReplaceOnPositionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to perform mass replace for: {0} transactions?.
        /// </summary>
        public static string QuestionDoYouWantToPerformMassReplaceOnTransactionsFormat {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToPerformMassReplaceOnTransactionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you want to remove {0} position?.
        /// </summary>
        public static string QuestionDoYouWantToRemovePositionFormat {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToRemovePositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you want to remove {0} transaction?.
        /// </summary>
        public static string QuestionDoYouWantToRemoveTransactionFormat {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToRemoveTransactionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace match.
        /// </summary>
        public static string ReplaceMatch {
            get {
                return ResourceManager.GetString("ReplaceMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After change restart is required!.
        /// </summary>
        public static string RestartRequiredAfterChange {
            get {
                return ResourceManager.GetString("RestartRequiredAfterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save search criteria.
        /// </summary>
        public static string SaveSearchCriteria {
            get {
                return ResourceManager.GetString("SaveSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all/none.
        /// </summary>
        public static string SelectAllNone {
            get {
                return ResourceManager.GetString("SelectAllNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only top categories.
        /// </summary>
        public static string ShowTopCategories {
            get {
                return ResourceManager.GetString("ShowTopCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show transfers.
        /// </summary>
        public static string ShowTransfers {
            get {
                return ResourceManager.GetString("ShowTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin colors.
        /// </summary>
        public static string SkinColors {
            get {
                return ResourceManager.GetString("SkinColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin shape.
        /// </summary>
        public static string SkinShape {
            get {
                return ResourceManager.GetString("SkinShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements (columns) splitter.
        /// </summary>
        public static string SplitterValue {
            get {
                return ResourceManager.GetString("SplitterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock name.
        /// </summary>
        public static string StockName {
            get {
                return ResourceManager.GetString("StockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stocks Manager.
        /// </summary>
        public static string StocksManagerHeader {
            get {
                return ResourceManager.GetString("StocksManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tags Manager.
        /// </summary>
        public static string TagsManagerHeader {
            get {
                return ResourceManager.GetString("TagsManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions search.
        /// </summary>
        public static string TransactionSearch {
            get {
                return ResourceManager.GetString("TransactionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions search.
        /// </summary>
        public static string TransactionsSearch {
            get {
                return ResourceManager.GetString("TransactionsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string TransactionTypes {
            get {
                return ResourceManager.GetString("TransactionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Types Manager.
        /// </summary>
        public static string TypesManagerHeader {
            get {
                return ResourceManager.GetString("TypesManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update mode.
        /// </summary>
        public static string UpdateMode {
            get {
                return ResourceManager.GetString("UpdateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock.
        /// </summary>
        public static string UpdateStock {
            get {
                return ResourceManager.GetString("UpdateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock balance.
        /// </summary>
        public static string UpdateStockBalance {
            get {
                return ResourceManager.GetString("UpdateStockBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock balance will be updated.
        ///Case: &quot;I just made a mistake and everything is wrong (balance and transaction)&quot;!.
        /// </summary>
        public static string UpdateStockBalanceTooltip {
            get {
                return ResourceManager.GetString("UpdateStockBalanceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use extended date picking mechanism.
        /// </summary>
        public static string UseExtendedDatePicker {
            get {
                return ResourceManager.GetString("UseExtendedDatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons for easier date picking.
        /// </summary>
        public static string UseExtendedDatePickerTooltip {
            get {
                return ResourceManager.GetString("UseExtendedDatePickerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User percent ownership.
        /// </summary>
        public static string UserPercentOwnership {
            get {
                return ResourceManager.GetString("UserPercentOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User stock.
        /// </summary>
        public static string UserStock {
            get {
                return ResourceManager.GetString("UserStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #,##0.00.
        /// </summary>
        public static string ValueFormat {
            get {
                return ResourceManager.GetString("ValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth.
        /// </summary>
        public static string Wealth {
            get {
                return ResourceManager.GetString("Wealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth plot.
        /// </summary>
        public static string WealthPlot {
            get {
                return ResourceManager.GetString("WealthPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard.
        /// </summary>
        public static string Wildcard {
            get {
                return ResourceManager.GetString("Wildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
