//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashManager_MVVM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashManager_MVVM.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add stock.
        /// </summary>
        public static string AddStock {
            get {
                return ResourceManager.GetString("AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Category Manager.
        /// </summary>
        public static string CategoryManagerHeader {
            get {
                return ResourceManager.GetString("CategoryManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default external stock.
        /// </summary>
        public static string DefaultExternalStock {
            get {
                return ResourceManager.GetString("DefaultExternalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default income type.
        /// </summary>
        public static string DefaultIncomeType {
            get {
                return ResourceManager.GetString("DefaultIncomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default outcome type.
        /// </summary>
        public static string DefaultOutcomeType {
            get {
                return ResourceManager.GetString("DefaultOutcomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default categories.
        /// </summary>
        public static string GenerateDefaultCategories {
            get {
                return ResourceManager.GetString("GenerateDefaultCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default stocks.
        /// </summary>
        public static string GenerateDefaultStocks {
            get {
                return ResourceManager.GetString("GenerateDefaultStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default tags.
        /// </summary>
        public static string GenerateDefaultTags {
            get {
                return ResourceManager.GetString("GenerateDefaultTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate default types.
        /// </summary>
        public static string GenerateDefaultTypes {
            get {
                return ResourceManager.GetString("GenerateDefaultTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate missing stocks.
        /// </summary>
        public static string GenerateMissingStocks {
            get {
                return ResourceManager.GetString("GenerateMissingStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate sample transactions.
        /// </summary>
        public static string GenerateSampleTransactions {
            get {
                return ResourceManager.GetString("GenerateSampleTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Home.
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string ImportHeader {
            get {
                return ResourceManager.GetString("ImportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        public static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manage.
        /// </summary>
        public static string ManageHeader {
            get {
                return ResourceManager.GetString("ManageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual stock update.
        /// </summary>
        public static string ManualStockUpdate {
            get {
                return ResourceManager.GetString("ManualStockUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass replace.
        /// </summary>
        public static string MassReplace {
            get {
                return ResourceManager.GetString("MassReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse.
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser.
        /// </summary>
        public static string Parser {
            get {
                return ResourceManager.GetString("Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform.
        /// </summary>
        public static string Perform {
            get {
                return ResourceManager.GetString("Perform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions search.
        /// </summary>
        public static string PositionSearch {
            get {
                return ResourceManager.GetString("PositionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save search criteria.
        /// </summary>
        public static string SaveSearchCriteria {
            get {
                return ResourceManager.GetString("SaveSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock name.
        /// </summary>
        public static string StockName {
            get {
                return ResourceManager.GetString("StockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stocks Manager.
        /// </summary>
        public static string StocksManagerHeader {
            get {
                return ResourceManager.GetString("StocksManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tags Manager.
        /// </summary>
        public static string TagsManagerHeader {
            get {
                return ResourceManager.GetString("TagsManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions search.
        /// </summary>
        public static string TransactionSearch {
            get {
                return ResourceManager.GetString("TransactionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Types Manager.
        /// </summary>
        public static string TypesManagerHeader {
            get {
                return ResourceManager.GetString("TypesManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User percent ownership.
        /// </summary>
        public static string UserPercentOwnership {
            get {
                return ResourceManager.GetString("UserPercentOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User stock.
        /// </summary>
        public static string UserStock {
            get {
                return ResourceManager.GetString("UserStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth.
        /// </summary>
        public static string Wealth {
            get {
                return ResourceManager.GetString("Wealth", resourceCulture);
            }
        }
    }
}
